[package]
authors = [
  "Tsiry Sandratraina <tsiry.sndr@fluentci.io>",
]
description = "DynamoDB Local Plugin for FluentCI"
keywords = [
  "dynamodb",
]
license = "MIT"
name = "dynamodb-local"
version = "0.1.1"
