[workspace]
default-members = [
  "apache",
  "caddy",
  "clickhouse",
  "cockroachdb",
  "consul",
  "consul-template",
  "couchdb",
  "daemon",
  "dragonflydb",
  "dynamodb-local",
  "elasticmq",
  "envconsul",
  "etcd",
  "httpbin",
  "mariadb",
  "meilisearch",
  "memcached",
  "minikube",
  "minio",
  "mongodb",
  "mysql",
  "nats",
  "nginx",
  "nsq",
  "php",
  "postgres",
  "rabbitmq",
  "redis",
  "stripe-mock",
  "temporal",
  "typesense",
  "vault",
]
members = [
  "apache",
  "caddy",
  "clickhouse",
  "cockroachdb",
  "consul",
  "consul-template",
  "couchdb",
  "daemon",
  "dragonflydb",
  "dynamodb-local",
  "elasticmq",
  "envconsul",
  "etcd",
  "httpbin",
  "mariadb",
  "meilisearch",
  "memcached",
  "minikube",
  "minio",
  "mongodb",
  "mysql",
  "nats",
  "nginx",
  "nsq",
  "php",
  "postgres",
  "rabbitmq",
  "redis",
  "stripe-mock",
  "temporal",
  "typesense",
  "vault",
]
resolver = "2"
