[workspace]
default-members = [
  "apache",
  "redis",
  "dragonflydb",
  "nginx",
  "caddy",
  "httpbin",
  "php",
  "meilisearch",
  "mysql",
  "mariadb",
  "postgres",
  "temporal",
  "rabbitmq",
  "typesense",
  "mongodb",
]
members = [
  "apache",
  "redis",
  "dragonflydb",
  "nginx",
  "caddy",
  "httpbin",
  "php",
  "meilisearch",
  "mysql",
  "mariadb",
  "postgres",
  "temporal",
  "rabbitmq",
  "typesense",
  "mongodb",
]
resolver = "2"
