[workspace]
default-members = ["apache", "redis", "dragonflydb", "nginx", "caddy", "httpbin", "php", "mysql"]
members = ["apache", "redis", "dragonflydb", "nginx", "caddy", "httpbin", "php", "mysql"]
resolver = "2"
