[workspace]
default-members = [
  "apache",
  "redis",
  "dragonflydb",
  "nginx",
  "caddy",
  "httpbin",
  "php",
  "mysql",
  "mariadb",
]
members = [
  "apache",
  "redis",
  "dragonflydb",
  "nginx",
  "caddy",
  "httpbin",
  "php",
  "mysql",
  "mariadb",
]
resolver = "2"
