[package]
authors = [
  "Tsiry Sandratraina <tsiry.sndr@fluentci.io>",
]
description = "Consul Template Plugin for FluentCI"
keywords = [
  "consul-template",
  "consul",
]
license = "MIT"
name = "consul-template"
version = "0.1.0"
