[package]
authors = [
  "Tsiry Sandratraina <tsiry.sndr@fluentci.io>",
]
description = "ElasticMQ Plugin for FluentCI"
keywords = [
  "elasticmq",
]
license = "MIT"
name = "elasticmq"
version = "0.1.0"
