[package]
authors = [
  "Tsiry Sandratraina <tsiry.sndr@fluentci.io>",
]
description = "Envconsul Plugin for FluentCI"
keywords = [
  "envconsul",
  "consul",
]
license = "MIT"
name = "envconsul"
version = "0.1.0"
