[package]
authors = [
  "Tsiry Sandratraina <tsiry.sndr@fluentci.io>",
]
description = "Stripe Mock Plugin for FluentCI"
keywords = [
  "stripe",
]
license = "MIT"
name = "stripe-mock"
version = "0.1.1"
