[package]
authors = [
  "Tsiry Sandratraina <tsiry.sndr@fluentci.io>",
]
description = "CockroachDB Plugin for FluentCI"
keywords = [
  "cockroachdb",
]
license = "MIT"
name = "cockroachdb"
version = "0.1.0"
