name: ci
on:
  push:
    branches:
      - main
    paths:
      - arangodb/**
      - .github/workflows/arangodb.yml
jobs:
  arangodb-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Fluent CI
        uses: fluentci-io/setup-fluentci@v5
        with:
          wasm: true
          plugin: rust
          args: |
            target_add wasm32-unknown-unknown
            build --release --target wasm32-unknown-unknown
          working-directory: arangodb
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Start arangodb Server
        run: |
          fluentci run target/wasm32-unknown-unknown/release/arangodb.wasm start
          fluentci ps
          fluentci status arangodb
          fluentci run target/wasm32-unknown-unknown/release/arangodb.wasm stop
        working-directory: arangodb
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NIX_CONFIG: extra-access-tokens = github.com=${{ secrets.GH_ACCESS_TOKEN }}
