name: ci
on:
  push:
    branches:
      - main
jobs:
  duckdb-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Fluent CI
        uses: fluentci-io/setup-fluentci@v5
        with:
          wasm: true
          plugin: rust
          args: |
            target_add wasm32-unknown-unknown
            build --release --target wasm32-unknown-unknown
          working-directory: duckdb
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Start Duckdb
        run: |
          fluentci run target/wasm32-unknown-unknown/release/duckdb.wasm start
          fluentci run target/wasm32-unknown-unknown/release/duckdb.wasm stop duckdb
        working-directory: duckdb
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NIX_CONFIG: extra-access-tokens = github.com=${{ secrets.GH_ACCESS_TOKEN }}
