name: ci
on:
  push:
    branches:
      - main
    paths:
      - minikube/**
      - .github/workflows/minikube.yml
jobs:
  minikube-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Fluent CI
        uses: fluentci-io/setup-fluentci@v5
        with:
          wasm: true
          plugin: rust
          args: |
            target_add wasm32-unknown-unknown
            build --release --target wasm32-unknown-unknown
          working-directory: minikube
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Remove preinstalled minikube
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo rm /usr/local/bin/minikube
      - name: Setup Docker
        if: ${{ matrix.os == 'macos-12' }}
        run: |
          brew install docker lima
          limactl start template://docker
          docker context create lima-docker --docker "host=unix:///Users/runner/.lima/docker/sock/docker.sock
      - name: Start minikube server
        run: |
          fluentci run target/wasm32-unknown-unknown/release/minikube.wasm start
          fluentci run target/wasm32-unknown-unknown/release/minikube.wasm stop
        working-directory: minikube
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NIX_CONFIG: extra-access-tokens = github.com=${{ secrets.GH_ACCESS_TOKEN }}
