name: ci
on:
  push:
    branches:
      - main
    paths:
      - mongodb/**
      - .github/workflows/mongodb.yml
jobs:
  mongodb-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Fluent CI
        uses: fluentci-io/setup-fluentci@v5
        with:
          wasm: true
          plugin: rust
          args: |
            target_add wasm32-unknown-unknown
            build --release --target wasm32-unknown-unknown
          working-directory: mongodb
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Start MongoDB Server
        run: |
          fluentci run target/wasm32-unknown-unknown/release/mongo.wasm start
          fluentci run target/wasm32-unknown-unknown/release/mongo.wasm stop
        working-directory: mongodb
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NIX_CONFIG: extra-access-tokens = github.com=${{ secrets.GH_ACCESS_TOKEN }}
