name: ci
on:
  push:
    branches:
      - main
    paths:
      - php/**
      - .github/workflows/php.yml
jobs:
  php-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Fluent CI
        uses: fluentci-io/setup-fluentci@v5
        with:
          wasm: true
          plugin: rust
          args: |
            target_add wasm32-unknown-unknown
            build --release --target wasm32-unknown-unknown
          working-directory: php
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Start Httpbin Server
        run: |
          fluentci run ../target/wasm32-unknown-unknown/release/php_fpm.wasm start
          fluentci run ../target/wasm32-unknown-unknown/release/php_fpm.wasm stop httpbin
        working-directory: php/example
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NIX_CONFIG: extra-access-tokens = github.com=${{ secrets.GH_ACCESS_TOKEN }}
