name: ci
on:
  push:
    branches:
      - main
    paths:
      - postgres/**
      - .github/workflows/postgres.yml
jobs:
  postgres-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Uninstall Postgres
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get remove postgresql postgresql-contrib
          sudo apt-get --purge remove postgresql postgresql-contrib
          sudo apt-get autoremove
          sudo apt-get autoclean
      - name: Setup Fluent CI
        uses: fluentci-io/setup-fluentci@v5
        with:
          wasm: true
          plugin: rust
          args: |
            target_add wasm32-unknown-unknown
            build --release --target wasm32-unknown-unknown
          working-directory: postgres
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Start Postgres Server
        run: |
          fluentci run target/wasm32-unknown-unknown/release/postgres.wasm start
          fluentci run target/wasm32-unknown-unknown/release/postgres.wasm stop
        working-directory: postgres
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NIX_CONFIG: extra-access-tokens = github.com=${{ secrets.GH_ACCESS_TOKEN }}
